# Optimizers configuration

  SA:
    enabled: True
    description: Simulated Annealing
    generator: discrete
  ga:
    enabled: False
    description: Genetic algorithm with parent selection, mutation, elitism
    generator: discrete
  pso:
    enabled: False
    description: Particle swarm
    generator: continuous
